### ISSUE TITLE
SBT dependency reference in readme broken

### ISSUE THREAD

**Issue by evbo** [pygmalios/reactiveinflux-spark#2]
I get errors with sbt library you referenced in the readme. Consider just pasting a link to maven central or update it with:

```
libraryDependencies += "com.pygmalios" %% "reactiveinflux-spark" % "1.4.0.10.0.5.1"
```

(which works for me currently)

**Comment by amoussoubaruch** [comment]
Thanks! It's work for me also.
I use spark 2.10 and influxdb 0.12

**Comment by amoussoubaruch** [comment]
Hi,

I build my jar after coding what i want to do with influxb dependencies. It compile well but when i run jar i have this error. I don't find where is the problem. Can you give me please an idea?

`17/06/11 14:05:58 INFO client.StandaloneAppClient$ClientEndpoint: Executor updated: app-20170611140558-0039/2 is now RUNNING
17/06/11 14:05:59 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHandler@3af37506{/metrics/json,null,AVAILABLE}
17/06/11 14:05:59 INFO scheduler.EventLoggingListener: Logging events to hdfs:///mnt/spark/logs/app-20170611140558-0039
17/06/11 14:05:59 INFO cluster.StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
Exception in thread "main" java.lang.NoClassDefFoundError: com/pygmalios/reactiveinflux/Point$
	at InfluxKafka$.main(InfluxKafka.scala:22)
	at InfluxKafka.main(InfluxKafka.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:738)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: com.pygmalios.reactiveinflux.Point$
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 11 more
17/06/11 14:05:59 INFO spark.SparkContext: Invoking stop() from shutdown hook
17/06/11 14:05:59 INFO server.ServerConnector: Stopped ServerConnector@2fd1731c{HTTP/1.1}{0.0.0.0:4040}
17/06/11 14:05:59 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@55f3c410{/stages/stage/kill,null,UNAVAILABLE}
17/06/11 14:05:59 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@460f76a6{/jobs/job/kill,null,UNAVAILABLE}
17/06/11 14:05:59 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@11dee337{/api,null,UNAVAILABLE}
17/06/11 14:05:59 INFO handler.ContextHandler: Stopped o.s.j.s.ServletContextHandler@7997b197{/,null,UNAVAILABLE}
`
